version: '3.7'

services:
  tor:
    image: lncm/tor:0.4.6.7
    container_name: tor
    volumes:
      - ${PWD}/tor/data:/etc/tor
      - ${PWD}/tor/data:/var/lib/tor
      - ${PWD}/tor/run:/var/run/tor
    restart: on-failure
    network_mode: host
    expose:
      - "9050"
      - "9051"
    stop_grace_period: 10m30s
  lightningd:
    container_name: lightningd
#    image: elementsproject/lightningd:v0.10.0
    image: azuchi/lightningd:v0.10.1
    depends_on:
      - tor
    restart: on-failure
    stop_grace_period: 5m30s
    network_mode: host
    environment:
      - LIGHTNINGD_NETWORK=bitcoin
    command:
      - --bitcoin-rpcconnect=$BITCOIN_RPC_HOST
      - --bitcoin-rpcport=$BITCOIN_RPC_PORT
      - --bitcoin-rpcuser=$BITCOIN_RPC_USER
      - --bitcoin-rpcpassword=$BITCOIN_RPC_PASSWORD
      - --network=bitcoin
      - --alias=$LIGHTNING_ALIAS
      - --rgb=$LIGHTNING_RGB
      - --log-level=debug
      - --proxy=127.0.0.1:9050
      - --bind-addr=127.0.0.1:9735
      - --addr=statictor:127.0.0.1:9051
      - --always-use-proxy=true
    expose:
      - "9735"
    volumes:
      - ${PWD}/lightningd:/root/.lightning
      - ${PWD}/bitcoin:/etc/bitcoin
