version: '3.7'

services:
#  tor:
#    container_name: tor
#    image: lncm/tor:0.4.5.7@sha256:a83e0d9fd1a35adf025f2f34237ec1810e2a59765988dce1dfb222ca8ef6583c
#    restart: on-failure
#    volumes:
#      - ${PWD}/tor/torrc:/etc/tor/torrc
#      - ${PWD}/tor/data:/var/lib/tor/
#      - ${PWD}/tor/run:/var/run/tor/
#    ports:
#      - "127.0.0.1:$TOR_PROXY_PORT:$TOR_PROXY_PORT"
#    networks:
#      default:
#        ipv4_address: $TOR_PROXY_IP
  lightningd:
    container_name: lightningd
    image: elementsproject/lightningd:v0.10.0
#    image: azuchi/lightningd:v0.10.1
    command:
      - --bitcoin-rpcconnect=$BITCOIN_RPC_HOST
      - --bitcoin-rpcport=$BITCOIN_RPC_PORT
      - --bitcoin-rpcuser=$BITCOIN_RPC_USER
      - --bitcoin-rpcpassword=$BITCOIN_RPC_PASSWORD
      - --network=bitcoin
      - --alias=$LIGHTNING_ALIAS
      - --rgb=$LIGHTNING_RGB
      - --log-level=debug
    expose:
      - "9735"
    ports:
      - "0.0.0.0:9735:9735"
    volumes:
      - ${PWD}/lightningd:/root/.lightning
      - ${PWD}/bitcoin:/etc/bitcoin
